services:
  db3:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: survey_db
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: survey_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - survey-net

  pgadmin3:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/.pgpass:/pgpass
    ports:
      - "5052:80"
    networks:
      - survey-net
    depends_on:
      - db3

  backend3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - JAVA_OPTS=-Duser.timezone=Europe/Budapest
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    ports:
      - "8082:8080"
      - "5005:5005"
    networks:
      - survey-net
    depends_on:
      - db3

#  frontend3:
#    build:
#      context: ../surveys-frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3002:80"
#    depends_on:
#      - backend3

volumes:
  postgres_data:
  pgadmin_data:

networks:
  survey-net:
    driver: bridge