jakarta:
  application:
    name: survey-hw-jakarta

  servlet:
    multipart:
      enabled: true
      resolve-lazily: false
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO